### ISSUE TITLE
Change the data source logic for the Baths field on Featured Listings Widget

### ISSUE THREAD

**Issue by spmiller2** [SimplyRETS/simplyretswp#160]
Currently the `bath(s)` field on Featured listings uses `.property.fullBaths`

It would be better to use the logic from the property detail page field (under the photos), which appears to be

     if the returned data includes `.property.bathrooms` use that.
     if the returned data does not, then use `.property.bathsFull` 

It would be nice if the label could be data-source aware as well

    When the data comes from `.property.bathrooms` then print bath(s)
    When the data comes from `.property.bathsFull` then print Full Bathroom(s)

![image](https://user-images.githubusercontent.com/45745190/76313834-f72ead00-6292-11ea-927f-c4172016f1bd.png)

**Comment by CodyReichert** [comment]
I fixed this behavior in #161 and will release as `v2.8.8` later today after doing a little more testing.

Worth noting that this was fixed _everywhere_ we show "* baths" in a listing preview:

- `[sr_listings]`/`[sr_search_form]`/`[sr_map_search]` list views
- Featured listing widget, Agents listing widgets, Random listing widget
- `[sr_listings_slider]`

So that everything will be consistent across all of the short-codes.
